# Generated by Django 2.2.1 on 2019-10-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='email',
            field=models.EmailField(default=False, max_length=244),
        ),
        migrations.AddField(
            model_name='new_user',
            name='firstname',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='new_user',
            name='img',
            field=models.ImageField(default=False, max_length=1000, upload_to=''),
        ),
        migrations.AddField(
            model_name='new_user',
            name='lastname',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='new_user',
            name='password',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='new_user',
            name='username',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
